name: ci
on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - 'README.md'

  workflow_dispatch:
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace --parallel

      - name: Upload libColorRes aar
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libColorRes
          retention-days: 3
          path: |
            ./libColorRes/build/outputs/aar/*-release.aar

      - name: Upload libUtil aar
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libUtil
          retention-days: 3
          path: |
            ./libUtil/build/outputs/aar/*-release.aar

      - name: Upload libPref aar
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libPref
          retention-days: 3
          path: |
            ./libPref/build/outputs/aar/*-release.aar

      - name: Upload libTint aar
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libTint
          retention-days: 3
          path: |
            ./libTint/build/outputs/aar/*-release.aar



